(function () {
  const maps = [
    { id: "achiran", name: "Achiran", thumbnail: "assets/map-thumbnails/achiran/thumbnail.webp" },
    { id: "aegean", name: "Aegean", thumbnail: "assets/map-thumbnails/aegean/thumbnail.webp" },
    { id: "africa", name: "Africa", thumbnail: "assets/map-thumbnails/africa/thumbnail.webp" },
    { id: "alps", name: "Alps", thumbnail: "assets/map-thumbnails/alps/thumbnail.webp" },
    { id: "amazonriver", name: "Amazon River", thumbnail: "assets/map-thumbnails/amazonriver/thumbnail.webp" },
    { id: "antarctica", name: "Antarctica", thumbnail: "assets/map-thumbnails/antarctica/thumbnail.webp" },
    { id: "southamerica", name: "Americas", thumbnail: "assets/map-thumbnails/southamerica/thumbnail.webp" },
    { id: "archipelagosea", name: "Archipelago Sea", thumbnail: "assets/map-thumbnails/archipelagosea/thumbnail.webp" },
    { id: "arctic", name: "Arctic", thumbnail: "assets/map-thumbnails/arctic/thumbnail.webp" },
    { id: "asia", name: "Asia", thumbnail: "assets/map-thumbnails/asia/thumbnail.webp" },
    { id: "australia", name: "Australia", thumbnail: "assets/map-thumbnails/australia/thumbnail.webp" },
    { id: "baikal", name: "Baikal", thumbnail: "assets/map-thumbnails/baikal/thumbnail.webp" },
    { id: "bajacalifornia", name: "Baja California", thumbnail: "assets/map-thumbnails/bajacalifornia/thumbnail.webp" },
    { id: "beringsea", name: "Bering Sea", thumbnail: "assets/map-thumbnails/beringsea/thumbnail.webp" },
    { id: "beringstrait", name: "Bering Strait", thumbnail: "assets/map-thumbnails/beringstrait/thumbnail.webp" },
    { id: "betweentwoseas", name: "Between Two Seas", thumbnail: "assets/map-thumbnails/betweentwoseas/thumbnail.webp" },
    { id: "blacksea", name: "Black Sea", thumbnail: "assets/map-thumbnails/blacksea/thumbnail.webp" },
    { id: "bosphorusstraits", name: "Bosphorus Straits", thumbnail: "assets/map-thumbnails/bosphorusstraits/thumbnail.webp" },
    { id: "britannia", name: "Britannia", thumbnail: "assets/map-thumbnails/britannia/thumbnail.webp" },
    { id: "britanniaclassic", name: "Britannia Classic", thumbnail: "assets/map-thumbnails/britanniaclassic/thumbnail.webp" },
    { id: "caucasus", name: "Caucasus", thumbnail: "assets/map-thumbnails/caucasus/thumbnail.webp" },
    { id: "conakry", name: "Conakry", thumbnail: "assets/map-thumbnails/conakry/thumbnail.webp" },
    { id: "deglaciatedantarctica", name: "Deglaciated Antarctica", thumbnail: "assets/map-thumbnails/deglaciatedantarctica/thumbnail.webp" },
    { id: "didier", name: "Didier", thumbnail: "assets/map-thumbnails/didier/thumbnail.webp" },
    { id: "didierfrance", name: "Didier (France)", thumbnail: "assets/map-thumbnails/didierfrance/thumbnail.webp" },
    { id: "dyslexdria", name: "Dyslexdria", thumbnail: "assets/map-thumbnails/dyslexdria/thumbnail.webp" },
    { id: "eastasia", name: "East Asia", thumbnail: "assets/map-thumbnails/eastasia/thumbnail.webp" },
    { id: "europe", name: "Europe", thumbnail: "assets/map-thumbnails/europe/thumbnail.webp" },
    { id: "falklandislands", name: "Falkland Islands", thumbnail: "assets/map-thumbnails/falklandislands/thumbnail.webp" },
    { id: "faroeislands", name: "Faroe Islands", thumbnail: "assets/map-thumbnails/faroeislands/thumbnail.webp" },
    { id: "fourislands", name: "Four Islands", thumbnail: "assets/map-thumbnails/fourislands/thumbnail.webp" },
    { id: "gatewaytotheatlantic", name: "Gateway to the Atlantic", thumbnail: "assets/map-thumbnails/gatewaytotheatlantic/thumbnail.webp" },
    { id: "greatlakes", name: "Great Lakes", thumbnail: "assets/map-thumbnails/greatlakes/thumbnail.webp" },
    { id: "gulfofstlawrence", name: "Gulf of St. Lawrence", thumbnail: "assets/map-thumbnails/gulfofstlawrence/thumbnail.webp" },
    { id: "halkidiki", name: "Halkidiki", thumbnail: "assets/map-thumbnails/halkidiki/thumbnail.webp" },
    { id: "hawaii", name: "Hawaii", thumbnail: "assets/map-thumbnails/hawaii/thumbnail.webp" },
    { id: "iceland", name: "Iceland", thumbnail: "assets/map-thumbnails/iceland/thumbnail.webp" },
    { id: "italia", name: "Italia", thumbnail: "assets/map-thumbnails/italia/thumbnail.webp" },
    { id: "japan", name: "Japan", thumbnail: "assets/map-thumbnails/japan/thumbnail.webp" },
    { id: "lemnos", name: "Lemnos", thumbnail: "assets/map-thumbnails/lemnos/thumbnail.webp" },
    { id: "lisbon", name: "Lisbon", thumbnail: "assets/map-thumbnails/lisbon/thumbnail.webp" },
    { id: "losangeles", name: "Los Angeles", thumbnail: "assets/map-thumbnails/losangeles/thumbnail.webp" },
    { id: "luna", name: "Luna", thumbnail: "assets/map-thumbnails/luna/thumbnail.webp" },
    { id: "manicouagan", name: "Manicouagan", thumbnail: "assets/map-thumbnails/manicouagan/thumbnail.webp" },
    { id: "marenostrum", name: "Mare Nostrum", thumbnail: "assets/map-thumbnails/marenostrum/thumbnail.webp" },
    { id: "mars", name: "Mars", thumbnail: "assets/map-thumbnails/mars/thumbnail.webp" },
    { id: "mediterranean", name: "Mediterranean", thumbnail: "assets/map-thumbnails/mediterranean/thumbnail.webp" },
    { id: "mena", name: "MENA", thumbnail: "assets/map-thumbnails/mena/thumbnail.webp" },
    { id: "milkyway", name: "Milky Way", thumbnail: "assets/map-thumbnails/milkyway/thumbnail.webp" },
    { id: "montreal", name: "Montreal", thumbnail: "assets/map-thumbnails/montreal/thumbnail.webp" },
    { id: "newyorkcity", name: "New York City", thumbnail: "assets/map-thumbnails/newyorkcity/thumbnail.webp" },
    { id: "niledelta", name: "Nile Delta", thumbnail: "assets/map-thumbnails/niledelta/thumbnail.webp" },
    { id: "northamerica", name: "North America", thumbnail: "assets/map-thumbnails/northamerica/thumbnail.webp" },
    { id: "oceania", name: "Oceania", thumbnail: "assets/map-thumbnails/oceania/thumbnail.webp" },
    { id: "pangaea", name: "Pangaea", thumbnail: "assets/map-thumbnails/pangaea/thumbnail.webp" },
    { id: "passage", name: "Passage", thumbnail: "assets/map-thumbnails/passage/thumbnail.webp" },
    { id: "pluto", name: "Pluto", thumbnail: "assets/map-thumbnails/pluto/thumbnail.webp" },
    { id: "sanfrancisco", name: "San Francisco", thumbnail: "assets/map-thumbnails/sanfrancisco/thumbnail.webp" },
    { id: "sierpinski", name: "Sierpinski", thumbnail: "assets/map-thumbnails/sierpinski/thumbnail.webp" },
    { id: "straitofgibraltar", name: "Strait of Gibraltar", thumbnail: "assets/map-thumbnails/straitofgibraltar/thumbnail.webp" },
    { id: "straitofhormuz", name: "Strait of Hormuz", thumbnail: "assets/map-thumbnails/straitofhormuz/thumbnail.webp" },
    { id: "straitofmalacca", name: "Strait of Malacca", thumbnail: "assets/map-thumbnails/straitofmalacca/thumbnail.webp" },
    { id: "surrounded", name: "Surrounded", thumbnail: "assets/map-thumbnails/surrounded/thumbnail.webp" },
    { id: "svalmel", name: "Svalmel", thumbnail: "assets/map-thumbnails/svalmel/thumbnail.webp" },
    { id: "thebox", name: "The Box", thumbnail: "assets/map-thumbnails/thebox/thumbnail.webp" },
    { id: "tradersdream", name: "Traders Dream", thumbnail: "assets/map-thumbnails/tradersdream/thumbnail.webp" },
    { id: "twolakes", name: "Two Lakes", thumbnail: "assets/map-thumbnails/twolakes/thumbnail.webp" },
    { id: "world", name: "World", thumbnail: "assets/map-thumbnails/world/thumbnail.webp" },
    { id: "yenisei", name: "Yenisei", thumbnail: "assets/map-thumbnails/yenisei/thumbnail.webp" },
  ];

  globalThis.OPENFRONT_MAPS = Object.freeze(maps);
})();
